### ISSUE TITLE
Orphan Image

### ISSUE THREAD

**Issue by therobfather3** [CM2Walki/steamcmd#1]
I might be doing it wrong, but when I do a docker pull command, it seems to download correctly, but shows up as an orphan image.

I'm not super sophisticated with my unraid yet, so it could be something I'm doing wrong. Any chance of some help?

**Comment by CM2Walki** [comment]
Hey,
I just pulled it myself to check, it gets tagged properly as "cm2network/steamcmd:latest", same thing happens if I run it directly using.
docker run -it --name=steamcmd cm2network/steamcmd bash
Are you already using a child image that depends on an older version of cm2network/steamcmd? Because that might cause it to be tagged as <none>.

**Comment by CM2Walki** [comment]
Locked due to inactivity.
